# Generated by Django 5.0.1 on 2024-02-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id_client', models.IntegerField()),
                ('order_id_order', models.IntegerField()),
            ],
        ),
    ]
